# Generated by Django 3.0.8 on 2020-08-24 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата')),
                ('breakdown', models.TextField(blank=True, verbose_name='Поломки')),
                ('chancery', models.TextField(blank=True, verbose_name='Канцелярия')),
                ('grocery', models.TextField(blank=True, verbose_name='Бакалея(Чай/кофе/печенье)')),
                ('house_chemicals', models.TextField(blank=True, verbose_name='Бытовая химия')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Было потрачено')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RubruckNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
            },
        ),
        migrations.AlterModelOptions(
            name='classmodel',
            options={'ordering': ['groups', 'date'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.RemoveField(
            model_name='homeworkmodel',
            name='slug',
        ),
        migrations.AddField(
            model_name='classmodel',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='classmodel',
            name='room_link',
            field=models.URLField(null=True, verbose_name='Ссылка на комнату занятия'),
        ),
        migrations.AddField(
            model_name='courseuser',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Онлайн?'),
        ),
        migrations.AddField(
            model_name='homeworkmodel',
            name='comment_file',
            field=models.FileField(blank=True, upload_to='file/comment_file/', verbose_name='Файл к комментарию'),
        ),
        migrations.AddField(
            model_name='homeworkmodel',
            name='comment_teacher',
            field=models.TextField(blank=True, verbose_name='Комментарий учителя'),
        ),
        migrations.AddField(
            model_name='homeworkteachermodel',
            name='attempts',
            field=models.IntegerField(default=3, verbose_name='Количество попыток'),
        ),
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, upload_to='news/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='news',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/news/'),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='homeworkmodel',
            name='rating',
            field=models.PositiveIntegerField(blank=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='homeworkmodel',
            name='status',
            field=models.CharField(choices=[('Проверено', 'Проверено'), ('Не проверено', 'Не проверено'), ('Не сдано', 'Не сдано')], default='Не проверено', max_length=300),
        ),
        migrations.AlterField(
            model_name='homeworkteachermodel',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='homeworkteachermodel',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Ссылка дз'),
        ),
        migrations.AlterField(
            model_name='materialtext',
            name='class_field',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_school.ClassModel', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='materialtext',
            name='img',
            field=models.ImageField(blank=True, default='images/materials/Rectangle.svg', upload_to='images/materials/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='materialtext',
            name='url',
            field=models.URLField(blank=True, default=None, max_length=100, verbose_name='Ссылка на материалы'),
        ),
        migrations.AlterField(
            model_name='materialvideo',
            name='class_field',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_school.ClassModel', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='materialvideo',
            name='url',
            field=models.URLField(blank=True, default=None, max_length=100, null=True, verbose_name='Ссылка на материалы'),
        ),
        migrations.AddField(
            model_name='news',
            name='rubrick',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_school.RubruckNews'),
        ),
    ]
