# Generated by Django 3.0.8 on 2020-08-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0002_auto_20200824_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance',
            field=models.CharField(choices=[('Присутствует', 'Присутствует'), ('Отсутствует', 'Отсутствует'), ('Отсутствует по уважительной причине', 'Отсутствует по уважительной причине')], default='Отсутствует', max_length=300),
        ),
    ]
