# Generated by Django 3.0.8 on 2020-08-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0002_auto_20200824_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='rubrick',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager_school.RubruckNews'),
        ),
    ]
