# Generated by Django 3.0.8 on 2020-08-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0002_auto_20200817_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkteachermodel',
            name='attempts',
            field=models.IntegerField(default=3, verbose_name='Количество попыток'),
        ),
    ]
