# Generated by Django 3.0.8 on 2020-07-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0003_auto_20200720_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classmodel',
            old_name='classes',
            new_name='classroom',
        ),
    ]
