# Generated by Django 3.0.8 on 2020-08-31 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0003_auto_20200831_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager_school.GroupModel'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название чата'),
        ),
    ]
