# Generated by Django 3.0.8 on 2020-08-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0003_auto_20200824_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseuser',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Онлайн?'),
        ),
    ]
