# Generated by Django 3.0.8 on 2020-08-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0003_auto_20200819_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, upload_to='news/', verbose_name='Изображение'),
        ),
    ]
