# Generated by Django 3.0.8 on 2020-09-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0003_auto_20200824_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='picture',
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/itnews', verbose_name='Изображение'),
        ),
    ]
