# Generated by Django 3.0.8 on 2020-08-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0004_news_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseuser',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Онлай?'),
        ),
    ]
