# Generated by Django 3.0.8 on 2020-08-22 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0004_news_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtext',
            name='class_field',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_school.ClassModel', verbose_name='Занятие'),
        ),
    ]
