# Generated by Django 3.0.8 on 2020-08-19 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0004_auto_20200819_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата')),
                ('breakdown', models.TextField(blank=True, verbose_name='Поломки')),
                ('chancery', models.TextField(blank=True, verbose_name='Канцелярия')),
                ('grocery', models.TextField(blank=True, verbose_name='Бакалея(Чай/кофе/печенье)')),
                ('house_chemicals', models.TextField(blank=True, verbose_name='Бытовая химия')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Было потрачено')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='classmodel',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='rubrick',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_school.RubruckNews'),
        ),
    ]
