# Generated by Django 3.0.8 on 2020-08-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0004_courseuser_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkmodel',
            name='description',
            field=models.TextField(blank=True, max_length=512, verbose_name='Описание ДЗ'),
        ),
    ]
