# Generated by Django 3.0.8 on 2020-09-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0004_auto_20200831_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='max_places_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество мест в аудитории'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/itnews', verbose_name='Изображение'),
        ),
    ]
