# Generated by Django 3.0.8 on 2020-08-21 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0005_auto_20200820_1431'),
        ('manager_school', '0003_auto_20200819_0835'),
    ]

    operations = [
    ]
