# Generated by Django 3.0.8 on 2020-08-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0005_auto_20200824_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkteachermodel',
            name='description',
            field=models.TextField(blank=True, max_length=512, verbose_name='Описание ДЗ'),
        ),
    ]
