# Generated by Django 3.0.8 on 2020-08-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0005_courseuser_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='room_link',
            field=models.URLField(null=True, verbose_name='Ссылка на комнату занятия'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Онлайн?'),
        ),
    ]
