# Generated by Django 3.0.8 on 2020-07-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0005_auto_20200720_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='classroom',
            field=models.ManyToManyField(default=None, to='manager_school.Classroom'),
        ),
    ]
