# Generated by Django 3.0.8 on 2020-08-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0006_auto_20200823_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='room_link',
            field=models.URLField(default='#', null=True, verbose_name='Ссылка на комнату занятия'),
        ),
    ]
