# Generated by Django 3.0.8 on 2020-08-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0006_auto_20200824_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='room_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на комнату занятия'),
        ),
    ]
