# Generated by Django 3.0.8 on 2020-07-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0006_auto_20200720_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkmodel',
            name='rating',
            field=models.IntegerField(default=0, max_length=2, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='homeworkmodel',
            name='status',
            field=models.CharField(choices=[('c', 'complite'), ('nv', 'not verified'), ('w', 'wrong')], default=None, max_length=300),
        ),
    ]
