# Generated by Django 3.0.8 on 2020-08-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0007_auto_20200824_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='room_link',
            field=models.URLField(null=True, verbose_name='Ссылка на комнату занятия'),
        ),
        migrations.AlterField(
            model_name='homeworkmodel',
            name='description',
            field=models.TextField(blank=True, max_length=700, verbose_name='Описание ДЗ'),
        ),
        migrations.AlterField(
            model_name='homeworkteachermodel',
            name='description',
            field=models.TextField(blank=True, max_length=700, verbose_name='Описание ДЗ'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, upload_to='news/', verbose_name='Изображение'),
        ),
    ]
