# Generated by Django 3.0.8 on 2020-07-20 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0007_auto_20200720_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkmodel',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Оценка'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('attendance', models.BooleanField(default=False, verbose_name='Присутствие')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='manager_school.ClassModel')),
                ('students', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
            },
        ),
    ]
