# Generated by Django 3.0.8 on 2020-08-28 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0007_auto_20200824_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Краткое описание')),
                ('description', models.TextField(max_length=512, verbose_name='Описание проблемы')),
                ('file', models.FileField(blank=True, upload_to='file/contact_admin/', verbose_name='Файл')),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In progress'), ('Waiting', 'Waiting')], default='Waiting', max_length=20, verbose_name='Статус лида')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления заявки')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за выполнение')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор заявки')),
            ],
            options={
                'verbose_name': 'Заявка администратору',
                'verbose_name_plural': 'Заявки администратору',
                'ordering': ['status', 'date'],
            },
        ),
    ]
