# Generated by Django 3.0.8 on 2020-07-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0008_auto_20200720_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtext',
            name='file',
            field=models.FileField(blank=True, upload_to='file/text_materials/', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='materialvideo',
            name='file',
            field=models.FileField(blank=True, upload_to='file/text_materials/', verbose_name='Файл'),
        ),
    ]
