# Generated by Django 3.0.8 on 2020-08-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0008_auto_20200823_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkmodel',
            name='status',
            field=models.CharField(choices=[('Проверено', 'Проверено'), ('Не проверено', 'Не проверено'), ('Не сдано', 'Не сдано')], default='n', max_length=300),
        ),
    ]
