# Generated by Django 3.0.8 on 2020-08-28 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0008_contactadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactadmin',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за выполнение'),
        ),
    ]
