# Generated by Django 3.0.8 on 2020-08-23 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0007_news_img'),
        ('manager_school', '0009_auto_20200823_1600'),
    ]

    operations = [
    ]
