# Generated by Django 3.0.8 on 2020-08-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0009_auto_20200828_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactadmin',
            name='response',
            field=models.TextField(blank=True, max_length=512, verbose_name='Ответ администратора'),
        ),
    ]
