# Generated by Django 3.0.8 on 2020-08-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0010_merge_20200823_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkmodel',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, upload_to='news/', verbose_name='Изображение'),
        ),
    ]
