# Generated by Django 3.0.8 on 2020-07-23 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0010_auto_20200723_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='students',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='att', to=settings.AUTH_USER_MODEL),
        ),
    ]
