# Generated by Django 3.0.8 on 2020-07-24 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0011_auto_20200723_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='students',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homeworkmodel',
            name='rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='homeworkmodel',
            name='status',
            field=models.CharField(choices=[('Проверено', 'Проверено'), ('Не проверено', 'Не проверено'), ('Не сдано', 'Не сдано')], default='nv', max_length=300),
        ),
    ]
