# Generated by Django 3.0.8 on 2020-09-01 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0011_auto_20200831_1228'),
        ('manager_school', '0003_auto_20200831_1130'),
        ('manager_school', '0008_auto_20200826_1148'),
    ]

    operations = [
    ]
