# Generated by Django 3.0.8 on 2020-07-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0011_auto_20200724_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestconversation',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата разговора'),
        ),
        migrations.AlterField(
            model_name='requestconversation',
            name='status',
            field=models.CharField(blank=True, choices=[('Ready', 'Ready'), ('Сall back', 'Сall back'), ('Denial', 'Denial')], max_length=20, null=True, verbose_name='Статус лида'),
        ),
    ]
