# Generated by Django 3.0.8 on 2020-08-24 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0005_auto_20200819_1900'),
        ('manager_school', '0011_auto_20200823_1947'),
    ]

    operations = [
    ]
