# Generated by Django 3.0.8 on 2020-08-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0012_merge_20200824_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkteachermodel',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='homeworkteachermodel',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Ссылка дз'),
        ),
    ]
