# Generated by Django 3.0.8 on 2020-07-27 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0012_auto_20200724_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageForAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, max_length=150, verbose_name='Тема')),
                ('description', models.TextField(verbose_name='Сообщение')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Админ')),
            ],
        ),
    ]
