# Generated by Django 3.0.8 on 2020-07-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0013_auto_20200727_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestconversation',
            options={'ordering': ['-date', 'status'], 'verbose_name': 'Разговор', 'verbose_name_plural': 'Разговоры'},
        ),
        migrations.RemoveField(
            model_name='materialtext',
            name='class_field',
        ),
        migrations.AddField(
            model_name='materialtext',
            name='class_field',
            field=models.ManyToManyField(to='manager_school.ClassModel', verbose_name='Занятие'),
        ),
        migrations.RemoveField(
            model_name='materialvideo',
            name='class_field',
        ),
        migrations.AddField(
            model_name='materialvideo',
            name='class_field',
            field=models.ManyToManyField(to='manager_school.ClassModel', verbose_name='Занятие'),
        ),
    ]
