# Generated by Django 3.0.8 on 2020-09-01 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0013_auto_20200901_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='recieved_date',
            new_name='date',
        ),
    ]
