# Generated by Django 3.0.8 on 2020-07-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0013_messageforadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkteachermodel',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homeworkteachermodel',
            name='url',
            field=models.URLField(blank=True, max_length=100, verbose_name='Ссылка дз'),
        ),
    ]
