# Generated by Django 3.0.8 on 2020-07-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0014_auto_20200728_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtext',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='educational_materials/books/'),
        ),
        migrations.AddField(
            model_name='materialvideo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='educational_materials/videos/'),
        ),
    ]
