# Generated by Django 3.0.8 on 2020-07-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0014_auto_20200728_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Тело')),
            ],
        ),
        migrations.AddField(
            model_name='classmodel',
            name='file',
            field=models.FileField(blank=True, upload_to='file/video_course/', verbose_name='Файл с видео'),
        ),
        migrations.DeleteModel(
            name='MessageForAdmin',
        ),
    ]
