# Generated by Django 3.0.8 on 2020-09-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0003_auto_20200831_1130'),
        ('manager_school', '0014_auto_20200901_1449'),
    ]

    operations = [
    ]
