# Generated by Django 3.0.8 on 2020-07-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0015_auto_20200728_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtext',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Ссылка на материалы'),
        ),
        migrations.AlterField(
            model_name='materialvideo',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Ссылка на материалы'),
        ),
    ]
