# Generated by Django 3.0.8 on 2020-09-11 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0015_merge_20200902_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Название группы расходов')),
            ],
            options={
                'verbose_name': 'Группа расходов',
                'verbose_name_plural': 'Группы расходов',
            },
        ),
        migrations.CreateModel(
            name='Expences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(blank=True, verbose_name='Описание затрат')),
                ('file', models.FileField(blank=True, upload_to='images/expences/', verbose_name='Чек/Фото')),
                ('price', models.FloatField(verbose_name='Сумма')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Expence', to='manager_school.ExpenceGroup', verbose_name='Группа расходов')),
            ],
            options={
                'verbose_name': 'Затраты',
                'verbose_name_plural': 'Затраты',
                'ordering': ['group', '-date'],
            },
        ),
    ]
