# Generated by Django 3.0.8 on 2020-07-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0015_auto_20200728_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='crate',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
