# Generated by Django 3.0.8 on 2020-07-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0016_auto_20200728_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='crate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, verbose_name='Тело'),
        ),
    ]
