# Generated by Django 3.0.8 on 2020-07-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0016_auto_20200728_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtext',
            name='class_field',
            field=models.ManyToManyField(related_name='material_text', to='manager_school.ClassModel', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='materialvideo',
            name='class_field',
            field=models.ManyToManyField(related_name='material_video', to='manager_school.ClassModel', verbose_name='Занятие'),
        ),
    ]
