# Generated by Django 3.0.8 on 2020-09-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0015_merge_20200914_1737'),
        ('manager_school', '0016_expencegroup_expences'),
    ]

    operations = [
    ]
