# Generated by Django 3.0.8 on 2020-09-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0017_merge_20200915_1259'),
        ('manager_school', '0004_auto_20200901_0811'),
    ]

    operations = [
    ]
