# Generated by Django 3.0.8 on 2020-07-29 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0017_auto_20200728_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups_manager', to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='manager_school.CourseUser', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='groups_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
    ]
