# Generated by Django 3.0.8 on 2020-07-28 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0017_auto_20200728_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='crate',
        ),
        migrations.AddField(
            model_name='news',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
