# Generated by Django 3.0.8 on 2020-07-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0014_auto_20200729_1325'),
        ('manager_school', '0018_auto_20200728_1503'),
    ]

    operations = [
    ]
