# Generated by Django 3.0.8 on 2020-09-17 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0018_merge_20200917_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtimeinterval',
            options={'ordering': ['time_from'], 'verbose_name': 'Временной промежуток занятости аудитории', 'verbose_name_plural': 'Временные промежутки занятости аудитории'},
        ),
        migrations.RemoveField(
            model_name='roomtimeinterval',
            name='is_free',
        ),
        migrations.AddField(
            model_name='roomtimeinterval',
            name='is_occupied',
            field=models.BooleanField(default=True, verbose_name='Занят?'),
        ),
        migrations.AlterField(
            model_name='roomtimeinterval',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_intervals', to='manager_school.Classroom', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='roomtimeinterval',
            name='time_from',
            field=models.TimeField(verbose_name='Начало промежутка'),
        ),
        migrations.AlterField(
            model_name='roomtimeinterval',
            name='time_to',
            field=models.TimeField(verbose_name='Окончание промежутка'),
        ),
    ]
