# Generated by Django 3.0.8 on 2020-07-29 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0019_auto_20200729_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=126, verbose_name='Номер договора')),
                ('date', models.DateField(verbose_name='Дата заключения договора')),
                ('price', models.FloatField(null=True, verbose_name='Цена')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manager_school.CourseUser', verbose_name='Курс')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manager_school.GroupModel', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
                'ordering': ['-date', '-price'],
            },
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_stages', models.BooleanField(default=True, verbose_name='Разбить на этапы?')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='manager_school.Contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
        migrations.CreateModel(
            name='PaymentStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/user/', verbose_name='Чек')),
                ('price', models.FloatField(null=True, verbose_name='Цена')),
                ('date', models.DateField(verbose_name='Дата платежа')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтвержден?')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_school.UserPayment', verbose_name='Оплата')),
            ],
            options={
                'verbose_name': 'Этап оплата',
                'verbose_name_plural': 'Этапы оплаты',
            },
        ),
    ]
