# Generated by Django 3.0.8 on 2020-09-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0019_auto_20200917_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtimeinterval',
            name='is_occupied',
            field=models.BooleanField(default=False, verbose_name='Занят?'),
        ),
    ]
