# Generated by Django 3.0.8 on 2020-07-29 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0020_contract_paymentstage_userpayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentstage',
            options={'ordering': ['-date'], 'verbose_name': 'Этап оплата', 'verbose_name_plural': 'Этапы оплаты'},
        ),
        migrations.AddField(
            model_name='contract',
            name='lead',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='manager_school.StudyRequest', verbose_name='Лид'),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='by_stages',
            field=models.BooleanField(default=False, verbose_name='Разбить на этапы?'),
        ),
    ]
