# Generated by Django 3.0.8 on 2020-09-17 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0020_auto_20200917_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtimeinterval',
            name='is_occupied',
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата занятия')),
                ('time_interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_school.RoomTimeInterval', verbose_name='Промежуток занятия')),
            ],
            options={
                'verbose_name': 'Резервирование аудитории',
                'verbose_name_plural': 'Резерирование аудитории',
                'ordering': ['date'],
            },
        ),
    ]
