# Generated by Django 3.0.8 on 2020-08-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0021_auto_20200729_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='studyrequest',
            name='tel_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
