# Generated by Django 3.0.8 on 2020-09-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0021_auto_20200917_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='time_interval',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='manager_school.RoomTimeInterval'),
        ),
        migrations.DeleteModel(
            name='Occupation',
        ),
    ]
