# Generated by Django 3.0.8 on 2020-08-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0022_auto_20200802_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='Контракт подписан?'),
        ),
    ]
