# Generated by Django 3.0.8 on 2020-09-17 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0022_auto_20200917_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtimeinterval',
            options={'ordering': ['room', 'time_from'], 'verbose_name': 'Временной промежуток занятости аудитории', 'verbose_name_plural': 'Временные промежутки занятости аудитории'},
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='time_interval',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classtime', to='manager_school.RoomTimeInterval'),
        ),
    ]
