# Generated by Django 3.0.8 on 2020-09-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0023_auto_20200917_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestconversation',
            name='status',
            field=models.CharField(blank=True, choices=[('Ready', 'Готово'), ('Сall back', 'Перезвонить'), ('Denial', 'Отказ')], max_length=20, null=True, verbose_name='Статус лида'),
        ),
        migrations.AlterField(
            model_name='studyrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('Ready', 'Готов к договору'), ('In Progress', 'В процессе'), ('Denial', 'Отказ')], max_length=20, verbose_name='Статус лида'),
        ),
    ]
