# Generated by Django 3.0.8 on 2020-08-03 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0023_contract_is_subscribed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentstage',
            options={'ordering': ['date'], 'verbose_name': 'Этап оплата', 'verbose_name_plural': 'Этапы оплаты'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(max_length=126, unique=True, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='slug',
            field=models.SlugField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='teacher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
    ]
