# Generated by Django 3.0.8 on 2020-09-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0024_auto_20200921_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseuser',
            name='fact',
            field=models.IntegerField(default=0, verbose_name='Кол-во дней переноса'),
        ),
    ]
