# Generated by Django 3.0.8 on 2020-08-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0024_auto_20200803_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='position',
            field=models.IntegerField(default=1, null=True, verbose_name='Номер занятия'),
        ),
    ]
