# Generated by Django 3.0.8 on 2020-09-28 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0025_courseuser_fact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseuser',
            name='fact',
        ),
    ]
