# Generated by Django 3.0.8 on 2020-08-03 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0025_classmodel_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classmodel',
            name='classroom',
        ),
        migrations.AddField(
            model_name='classmodel',
            name='classroom',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='classroom', to='manager_school.Classroom'),
        ),
    ]
