# Generated by Django 3.0.8 on 2020-08-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0026_auto_20200803_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='slug',
            field=models.SlugField(default=None, max_length=100, null=True),
        ),
    ]
