# Generated by Django 3.0.8 on 2020-08-05 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0019_merge_20200729_1610'),
        ('manager_school', '0027_auto_20200803_2105'),
    ]

    operations = [
    ]
