# Generated by Django 3.0.8 on 2020-08-05 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0028_merge_20200805_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='slug',
            field=models.SlugField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='homeworkmodel',
            name='class_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='manager_school.ClassModel', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='homeworkteachermodel',
            name='slug',
            field=models.SlugField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='homeworkteachermodel',
            name='url',
            field=models.URLField(max_length=100, null=True, verbose_name='Ссылка дз'),
        ),
        migrations.RemoveField(
            model_name='materialtext',
            name='class_field',
        ),
        migrations.AddField(
            model_name='materialtext',
            name='class_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_school.ClassModel', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='materialtext',
            name='url',
            field=models.URLField(max_length=100, null=True, verbose_name='Ссылка на материалы'),
        ),
        migrations.RemoveField(
            model_name='materialvideo',
            name='class_field',
        ),
        migrations.AddField(
            model_name='materialvideo',
            name='class_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_school.ClassModel', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='materialvideo',
            name='url',
            field=models.URLField(max_length=100, null=True, verbose_name='Ссылка на материалы'),
        ),
    ]
