# Generated by Django 3.0.8 on 2020-08-05 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0029_auto_20200805_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkmodel',
            name='class_field',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='manager_school.ClassModel', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='homeworkmodel',
            name='url',
            field=models.URLField(blank=True, default=None, max_length=100, null=True, verbose_name='Ссылка дз'),
        ),
        migrations.AlterField(
            model_name='homeworkteachermodel',
            name='url',
            field=models.URLField(default=None, max_length=100, null=True, verbose_name='Ссылка дз'),
        ),
        migrations.AlterField(
            model_name='materialtext',
            name='class_field',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_school.ClassModel', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='materialtext',
            name='url',
            field=models.URLField(default=None, max_length=100, null=True, verbose_name='Ссылка на материалы'),
        ),
        migrations.AlterField(
            model_name='materialvideo',
            name='class_field',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_school.ClassModel', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='materialvideo',
            name='url',
            field=models.URLField(default=None, max_length=100, null=True, verbose_name='Ссылка на материалы'),
        ),
    ]
