# Generated by Django 3.0.8 on 2020-08-06 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0032_auto_20200806_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
    ]
