# Generated by Django 3.0.8 on 2020-08-07 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0033_auto_20200806_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Время окончания занятия'),
        ),
        migrations.AddField(
            model_name='classmodel',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Время начала занятия'),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата проведения занятия'),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_management', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
    ]
