# Generated by Django 3.0.8 on 2020-08-07 17:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0034_auto_20200807_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Сообщение'),
        ),
    ]
