# Generated by Django 3.0.8 on 2020-08-13 08:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_school', '0035_auto_20200807_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtext',
            name='img',
            field=models.ImageField(default='images/materials/Rectangle.svg', upload_to='images/materials/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
